apiVersion: v1
kind: Service
metadata:
  name: nginx-cicd-service
  labels:
    app: nginx-cicd
spec:
  type: ClusterIP
  selector:
    app: nginx-cicd
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
